server:
  port: 8082

spring:
  application:
    name: springdatabasics
  datasource:
    url: "${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/spring_data_jpa_basics}"
    username: ${SPRING_DATASOURCE_USERNAME:neil}
    password: ${SPRING_DATASOURCE_PASSWORD:pass}
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true


logging:
  level:
    org.springframework.transaction.interceptor: TRACE
    org.springframework.orm.jpa: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

