server:
  port: 8082

spring:
  application:
    name: springdatabasics
  datasource:
    url: "${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/spring_data_jpa_basics}"
    username: ${SPRING_DATASOURCE_USERNAME:neil}
    password: ${SPRING_DATASOURCE_PASSWORD:pass}
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true

      # Enable second-level cache
        cache:
          use_second_level_cache: true
          use_query_cache: true
          region.factory_class: org.hibernate.cache.jcache.JCacheRegionFactory
          jcache.config: classpath:ehcache.xml
          provider_configuration_file_resource_path: classpath:ehcache.xml

#      # Enable query cache (optional)
#      hibernate.cache.use_query_cache: true
#
#      # Set the cache provider to Ehcache
#      hibernate.cache.region.factory_class: org.hibernate.cache.jcache.JCacheRegionFactory
#
#      # Ehcache configuration file path (optional, if you have a custom file)
#      hibernate.cache.jcache.config: classpath:ehcache.xml
#
#      # Hibernate's default cache provider (optional)
#      hibernate.cache.provider_configuration_file_resource_path: classpath:ehcache.xml

logging:
  level:
    org.springframework.transaction.interceptor: TRACE
    org.springframework.orm.jpa: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.orm.internal.QueryImpl: TRACE
    org.hibernate.engine.internal.StatefulPersistenceContext: TRACE

